spring.application.name=file-manager
storage.base-path=uploads

#ai.provider=local
ai.local.base-url=http://localhost:11434/api/generate
ai.local.model=qwen2.5:7b
ai.local.stream=false
#ai.api-key=changeme

spring.datasource.url=jdbc:postgresql://localhost:5432/file_manager
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB